#include <graphlib/structures>
#include <graphlib/external>
#include <iostream>
#include <mgl2/mgl.h>

int main(int argc, char const *argv[])
{
    using mgraph = gl::MGraph<double>;
    mgraph g(10);
    g.readFile("test/Input_edges"); //generated by python file
    mglGraph gr;
    gr.SetSize(1000, 1000);
    gl::external::saveImage(&gr, g, "k-"); // black lines
    gr.WritePNG("build/output.png");
    std::cout << "saved to build/output.png" << std::endl;
    return 0;
}
