#include <graphlib/structures>
#include <graphlib/external>
#include <iostream>
int main(int argc, char const *argv[]) {
  gl::graphMdd g(10);
  g.readFile("test/Input_edges"); //generated by python file
  std::ofstream out("build/test/OUTPUT.tex");
  gl::external::writeTikzToStream2(out, g);
  out.close();
  std::cout << "output written to build/test/OUTPUT.tex\n"
            << "Compile with:\n"
            << "cd build\n" 
            << "pdflatex test/OUTPUT.tex" <<  std::endl;
  return 0;
}
