#include "../../src/structures/MatrixGraph.hpp"
#include "../../src/io/WriteTikz.hpp"
#include <iostream>
int main(int argc, char const *argv[]) {
  using mgraph = gl::MGraph<double>;
  mgraph g(20);
  g.readFile("../test/io/edges.txt"); //generated by python file
  gl::writeTikzToStream2(std::cout, g);
  return 0;
}
