#include "../../src/structures/MatrixGraph.hpp"
#include "../../src/io/WriteImage.hpp"
#include <iostream>
#include <mgl2/mgl.h>

int main(int argc, char const *argv[])
{
    using mgraph = gl::MGraph<double>;
    mgraph g(10);
    g.readFile("../test/io/edges.txt"); //generated by python file
    mglGraph gr;
    gr.SetSize(1000, 1000);
    gl::saveImage(&gr, g, "k-"); // black lines
    gr.WritePNG("output.png");
    return 0;
}
