#include "../../src/structures/MatrixGraph.hpp"
#include "../../src/io/WriteTikz.hpp"
#include <iostream>
int main(int argc, char const *argv[]) {
  using mgraph = gl::MGraph<double>;
  mgraph g(10);
  g.readFile("../test/io/edges.txt"); //generated by python file
  std::ofstream out("OUTPUT.tex");
  gl::writeTikzToStream2(out, g);
  out.close();
  return 0;
}
